### ISSUE TITLE
Clarification on Patcher

### ISSUE THREAD

**Issue by titanbass1** [EzioTheDeadPoet/HighPolyHead-RaceMenuPatcher#3]
Hello EzioTheDeadPoet (love the name!). 
This isn't an issue, I apologize for my confusion, but I just wanted a clarification. If I understand this mod correctly, does it make sure every NPC detected in your game and mods uses, if applicable, a high poly head appropriate for their race? So basically any mod that patches NPCS to use HPH would not be needed? I don't think that includes mods like modpocalypse which add hair, tints, and other features, but I wanted to be doubly sure. 
Thanks.

**Comment by EzioTheDeadPoet** [comment]
No this Patcher doesn't change NPCs too High Poly Head. This Patcher changes the default head from Vanilla to HPH so during character creation you don't have to do it by hand for every character you start, mainly useful for People making guides so people can recreate their setup or modlist/collections to offer a streamlined experience.The changes it does make on NPCs are kinda the opposite reverting those changes for NPCs because NPC records are always missing parts they have identical to their race, because they inherit it from their race. But to make the default head different in race menu you need to edit the race default head. But doing so would leave every NPC with the blackface bug. And since most people are using NPC overhauls anyway this just patcher basically makes the NPCs independent from their race record by giving them the parts they normally inherited from their race, so that they still overwrite the race changes. This has the advantage that no one has to worry about their NPCs breaking with this Patcher.To force those NPCs to get all the HPH parts you could use the xEdit script from the HighPolyHead Mod, BUT changing that headpart will result in the blackface buf and require you to regenerate the facegen data and meshes and will make yourbl NPCs not look like your NPC Replacers anymore.If your NPC overhaul already uses HPH or any other pre-defined head mesh mod, then this Patcher skips altering those NPCs, because they are already save from the bug, at least regarding this patcher, but If your NPCs had the black face bug before running it they will still have it afterwards.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 9/23/22, 04:29 titanbass1 ***@***.***> wrote:

   
  Hello EzioTheDeadPoet (love the name!). This isn't an issue, I apologize for my confusion, but I just wanted a clarification. If I understand this mod correctly, does it make sure every NPC detected in your game and mods uses, if applicable, a high poly head appropriate for their race? So basically any mod that patches NPCS to use HPH would not be needed? I don't think that includes mods like modpocalypse which add hair, tints, and other features, but I wanted to be doubly sure. Thanks.

**Comment by Rhaevyn** [comment]
I've used this patcher before no problem.  This time around it said "Errored" and I got this, even though it finished the patch:

Writing to output: C:\Users\rhaev\AppData\Local\Temp\Synthesis\nccyla0f.xci\Workspace\High Poly Head Synth\1 - HighPolyHead-RaceMenuPatcher\High Poly Head Synth.esp
MissingModException Helps To Have A Map.esp: A referenced mod was not present on the load order being sorted against: Helps To Have A Map.esp.  This mod was referenced by MajorRecord: 005E4E:Dawnguard.esm    at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.SortMasters(List`1 modKeys)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ParallelWriteParameters parallelParam, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, ParallelWriteParameters parallelParam, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem, ParallelWriteParameters parallelWriteParams)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 566
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 419

What does this mean?
